### ISSUE TITLE
Same Site Error on Login with FF

### ISSUE THREAD

**Issue by nZac** [level12/keg-auth#112]
I am getting this error on Keg-Auth login pages in FF.

> Cookie “session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by guruofgentoo** [comment]
I'll need some more information on where you're seeing this. For our live sites that use keg-auth, I'm not seeing any warnings/errors. Is this with a particular project, or perhaps a 3rd-party lib changed that's not on one of our live sites yet?

**Comment by guruofgentoo** [comment]
As far as I know, this hasn't been a problem. Closing until we have a concrete example.
