### ISSUE TITLE
'disabled_utc' should be defined with the rest of the database fields

### ISSUE THREAD

**Issue by tjlevel12** [level12/keg-auth#116]
Right now, `disabled_utc` is defined after a number of hybrid properties, which is a non-obvious location. If there's no reason for it to be down there, can we move it up with the other database fields?

https://github.com/level12/keg-auth/blob/0107d6c65d4267c10aca997d6a191b5564dc21ad/keg_auth/model/__init__.py#L100-L110

**Comment by rsyring** [comment]
Also, is there any reason `server_default` is set explicitly to NULL?  That should be the default.
