### ISSUE TITLE
Better errors for User.testing_create() with invalid permission

### ISSUE THREAD

**Issue by rsyring** [level12/keg-auth#128]
If you happen to pass a non-existent permission into `UserMixin.testing_create()`, you end up with an error like:

```
sqlalchemy.orm.exc.FlushError: Can't flush None value found in collection User.permissions
```
The cause of which isn't immediately obvious.  

We have better error messages for this case in `ViewTestBase`.

https://github.com/level12/keg-auth/blob/5dd58bed1d986b29a78c9c1b5eabea861bd210f0/keg_auth/testing.py#L1190

I'd be in favor of moving that logic to `testing_create()`.

**Comment by guruofgentoo** [comment]
I actually centralized the check in the auth manager so it's not specific to either place. Both still call out to it, because we may have cases where we want the view tests to verify a set of permissions even if a user isn't being created right away.
