### ISSUE TITLE
Use B4 form from KegElements

### ISSUE THREAD

**Issue by calebsyring** [level12/keg-auth#131]
Change
https://github.com/level12/keg-auth/blob/5dd58bed1d986b29a78c9c1b5eabea861bd210f0/keg_auth/templates/keg_auth/crud-addedit.html#L1
to:
`{% import 'keg_elements/forms/horizontal_b4.html' as horizontal %}`

**Comment by calebsyring** [comment]
Looks like `form-base.html` also needs to be updated.

**Comment by guruofgentoo** [comment]
Changed in 0.5.0
