### ISSUE TITLE
UnknownHashError when user has a blank or null current password

### ISSUE THREAD

**Issue by pytrumpeter** [level12/keg-auth#160]
When the password stored in the database for a user is blank (`''`) or null, passlib cannot hash the value for comparison and an `UnknownHashError` is returned when `verify_password` is called.

Reference:  https://github.com/level12/gb-h2r/issues/919#issue-1321282556

**Comment by guruofgentoo** [comment]
We'll need more info on this one, as I have not been able to reproduce a test case.

**Comment by pytrumpeter** [comment]
@guruofgentoo I can't reproduce now with a null password value in the database, but I can with a blank password value by doing this in How2Recycle:

1. Set a user's password to '', not null
2. Remove the `try/catch` [here](https://github.com/level12/gb-h2r/blob/02fcf732bdc1693cdb7c0a06c2222a4853bce27e/how2recycle/extensions.py#L104), which we originally added to work around this issue
3. Attempt log in with that user, with any password.

**Comment by guruofgentoo** [comment]
The reason I wasn't reproducing a case is because the test suite uses plaintext passwords for speed. There doesn't seem to be a great way to mock in another crypt context later on, but we can mock the comparator to test that the exception is trapped.
