### ISSUE TITLE
Endpoint to Permission Map

### ISSUE THREAD

**Issue by nZac** [level12/keg-auth#23]
Copy from internal project:

> Hindsight is 20/20, but it's now quite clear that having a mapping between endpoints and required permissions would have been a huge win. Literally every place we use url_for, we must wrap it in a conditional to only show the link (or make it clickable, etc.) if the user has permission to access that endpoint. But since there is no mapping dictionary, we must hard code the mapping at every call site. Effectively not having the mapping means there is a ton of code duplication and a truckload of room for mistakes. In fact, there are whole swaths of links that are not properly checked for this condition. It's not a security issue, but a usability issue, since the links are clickable but will inevitably result in 403s for some users. Equally as bad is the difficulty in building abstractions around endpoints such that they are "permission-aware." Without the mapping, there is no generic way to write a form of url_for that considers permissions.

**Comment by guruofgentoo** [comment]
For what it's worth, this is what some of #10 refers to.

**Comment by nZac** [comment]
Perfect. Closing.
