### ISSUE TITLE
Add the ability to resend a user verification email

### ISSUE THREAD

**Issue by colanconnon** [level12/keg-auth#43]
If a user's verification email expires or for some reason does not work, there is no way to verify the user unless you delete them and add them again.

**Comment by rsyring** [comment]
> Add the ability for a super user to mark a user as verified when editing a user.

This wouldn't work.  The whole point of verification is to confirm access to an email address and set the user's password.  Admins, at least currently, should not be able to set a password.

**Comment by colanconnon** [comment]
@rsyring I edited the issue.
