### ISSUE TITLE
Adjust salt to not include `session_key` or `updated_utc`

### ISSUE THREAD

**Issue by colanconnon** [level12/keg-auth#45]
After discussion we decided to remove `updated_utc` and `session_key` from the salt. We are going to add a field to the users table `last_login_utc` and add that field to the salt. This field will get updated on flask_login's login event.

**Comment by guruofgentoo** [comment]
To be clear for those evaluating this issue, we'd be keeping the following in the salt:
- password hash
- verification status
- user display name (email, username, etc.)
