### ISSUE TITLE
the inflect dependency is AGPL and needs to be removed

### ISSUE THREAD

**Issue by rsyring** [level12/keg-auth#47]
it's viral.

Might as well add our own license while we are at it.

**Comment by rsyring** [comment]
Or ask upstream to change their license: https://github.com/jazzband/inflect/issues/29

**Comment by guruofgentoo** [comment]
FWIW, I think this is only used to pluralize object names for the CRUD view. We could switch to [inflection](https://inflection.readthedocs.io/en/latest/) which has the MIT license.

**Comment by guruofgentoo** [comment]
Upstream changed license to MIT.
