### ISSUE TITLE
Expand the documentation

### ISSUE THREAD

**Issue by tjlevel12** [level12/keg-auth#73]
Assorted items I've run into lately that don't seem to be covered by the documentation:

 * What migrations need to be written to support keg-auth?
 * What migrations are needed to support a keg-auth migration?
 * How are new auth entities added to the system?
    * Permissions
    * Groups
    * Bundles
 * What default values does keg-auth assume you'll have in your application?
    * `auth_manage` permission
    * what else?
 * What needs to be done to add the keg-auth management views to the blueprint / routes?

**Comment by guruofgentoo** [comment]
Answers we need to incorporate in the docs somewhere:
 * What migrations need to be written to support keg-auth?
   * best way forward is to use alembic's autogenerate
 * What migrations are needed to support a keg-auth migration?
   * autogenerate, as above
 * How are new auth entities added to the system?
   * this is documented in the readme, under Model (though that will need to be updated when #82 is completed)
 * What default values does keg-auth assume you'll have in your application?
    * `auth_manage` permission, not assumed to be present because an app may not want to allow permission to the auth crud views
    * `SERVER_NAME` setting, for sending emails from the command line
 * What needs to be done to add the keg-auth management views to the blueprint / routes?
    * also somewhat documented under Blueprints in the readme, but could include a reminder to add the generated blueprint to the app's blueprints list (`use_blueprints`)

A quickstart list would be helpful at the top of the readme, directing to following sections for details:
- install keg-auth
- set `SERVER_NAME` in config
- create and init AuthManager extension with permissions
- create the auth blueprint and link it to the keg app
- set up the registered entities
  - run alembic to autogenerate a revision
- use `requires_user` and `requires_permissions` decorators on views as needed
  - use `ViewTestBase` helper from `keg_auth.testing` to set up authenticated clients in integration tests
- set up a permission-based navigation tree with `NavItem` and `NavURL`, and use the template helpers to render

**Comment by guruofgentoo** [comment]
Handling in #99.
