### ISSUE TITLE
Make Permissions Dropdown a better control

### ISSUE THREAD

**Issue by nZac** [level12/keg-auth#84]
Selecting a lot of permissions is nearly impossible in the select2 dropdown on the group form. If we could make that a list of checkboxes that would be a big improvement. Though one of those left / right things might work well (like this: https://www.viralpatel.net/listbox-select-all-move-left-right-up-down-javascript/)?

 https://github.com/level12/keg-auth/blob/6685d527cdb69da8ace293093ae0061ddcd8fdbd/keg_auth/forms.py#L88

**Comment by calebsyring** [comment]
We should also have a select all button that uses javascript to select all checkboxes

**Comment by calebsyring** [comment]
Also, a minor front-end change in keg-elements should be pushed before the fix for this is merged.
